"""
BDD TEMPLATES
=============
Pre-built templates for pytest-bdd feature files and step definitions.
Coder Agent uses these as base when generating BDD test code.
"""

FEATURE_FILE_TEMPLATE = '''\
# {feature_name}.feature
# Generated by selenium-python-ai-agent

Feature: {feature_title}
  As a {role}
  I want to {goal}
  So that {benefit}

{scenarios}
'''

SCENARIO_TEMPLATE = '''\
  Scenario: {scenario_name}
{steps}
'''

STEP_DEFINITION_TEMPLATE = '''\
"""
Step Definitions for: {feature_name}
Generated by selenium-python-ai-agent
"""

import pytest
from pytest_bdd import given, when, then, parsers, scenarios
from selenium_agent.selenium.driver_factory import DriverFactory
from pages.{page_module} import {page_class}

# Link to feature file
scenarios("../features/{feature_name}.feature")


# ── Fixtures ──────────────────────────────────────────────────

@pytest.fixture
def driver():
    d = DriverFactory.create(browser="chrome", headless=True)
    yield d
    d.quit()


@pytest.fixture
def {page_fixture}(driver):
    page = {page_class}(driver)
    page.open({page_class}.URL)
    return page


# ── Step Definitions ─────────────────────────────────────────

{steps}
'''

GIVEN_STEP_TEMPLATE = '''\
@given("{step_text}")
def {func_name}({params}):
    """{step_text}"""
    {body}
'''

WHEN_STEP_TEMPLATE = '''\
@when("{step_text}")
def {func_name}({params}):
    """{step_text}"""
    {body}
'''

THEN_STEP_TEMPLATE = '''\
@then("{step_text}")
def {func_name}({params}):
    """{step_text}"""
    {body}
'''

CONFTEST_TEMPLATE = '''\
"""
conftest.py — pytest-bdd shared fixtures
Generated by selenium-python-ai-agent
"""

import pytest
from selenium_agent.selenium.driver_factory import DriverFactory


@pytest.fixture(scope="function")
def driver():
    """Create WebDriver instance for each test."""
    d = DriverFactory.create(browser="chrome", headless=True)
    yield d
    d.quit()
'''
