"""
BASE PAGE
=========
Base class for all Page Objects generated by the Coder Agent.

Every generated Page Object inherits from BasePage, which provides:
- Safe element finding with explicit waits
- Click, type, select helpers
- Scroll, hover, drag utilities
- Screenshot on failure
- Page state checks

Usage (in generated code):
    from selenium_agent.selenium.base_page import BasePage

    class LoginPage(BasePage):
        URL = "https://example.com/login"
        USERNAME_INPUT = (By.ID, "username")
        PASSWORD_INPUT = (By.ID, "password")
        LOGIN_BUTTON = (By.CSS_SELECTOR, "button[type='submit']")

        def login(self, username: str, password: str):
            self.type(self.USERNAME_INPUT, username)
            self.type(self.PASSWORD_INPUT, password)
            self.click(self.LOGIN_BUTTON)
"""

from __future__ import annotations
import os
from datetime import datetime
from typing import Union

from selenium.webdriver.common.by import By
from selenium.webdriver.common.action_chains import ActionChains
from selenium.webdriver.common.keys import Keys
from selenium.webdriver.remote.webdriver import WebDriver
from selenium.webdriver.remote.webelement import WebElement
from selenium.webdriver.support import expected_conditions as EC
from selenium.webdriver.support.ui import WebDriverWait, Select
from selenium.common.exceptions import (
    TimeoutException,
    NoSuchElementException,
    StaleElementReferenceException,
    ElementNotInteractableException,
    ElementClickInterceptedException,
)

# Type alias for locator tuples
Locator = tuple[str, str]


class BasePage:
    """
    Base class for all Page Objects.

    Provides safe, wait-aware wrappers around Selenium's WebDriver API.
    All generated Page Objects should inherit from this class.

    Args:
        driver: Selenium WebDriver instance
        timeout: Default explicit wait timeout in seconds (default: 10)
    """

    def __init__(self, driver: WebDriver, timeout: int = 10):
        self.driver = driver
        self.timeout = timeout
        self.wait = WebDriverWait(driver, timeout)

    # ──────────────────────────────────────────────
    # Navigation
    # ──────────────────────────────────────────────

    def open(self, url: str) -> "BasePage":
        """Navigate to a URL."""
        self.driver.get(url)
        return self

    def get_title(self) -> str:
        """Return current page title."""
        return self.driver.title

    def get_url(self) -> str:
        """Return current page URL."""
        return self.driver.current_url

    def refresh(self) -> "BasePage":
        """Refresh the current page."""
        self.driver.refresh()
        return self

    def go_back(self) -> "BasePage":
        """Navigate back in browser history."""
        self.driver.back()
        return self

    # ──────────────────────────────────────────────
    # Finding Elements (with explicit waits)
    # ──────────────────────────────────────────────

    def find(self, locator: Locator, timeout: int = None) -> WebElement:
        """
        Find element with explicit wait for visibility.

        Args:
            locator: Tuple of (By.strategy, value) e.g. (By.ID, "username")
            timeout: Override default timeout

        Returns:
            WebElement when found and visible

        Raises:
            TimeoutException: If element not visible within timeout
        """
        wait = WebDriverWait(self.driver, timeout or self.timeout)
        return wait.until(EC.visibility_of_element_located(locator))

    def find_clickable(self, locator: Locator, timeout: int = None) -> WebElement:
        """Find element and wait until it is clickable."""
        wait = WebDriverWait(self.driver, timeout or self.timeout)
        return wait.until(EC.element_to_be_clickable(locator))

    def find_all(self, locator: Locator, timeout: int = None) -> list[WebElement]:
        """Find all matching elements."""
        wait = WebDriverWait(self.driver, timeout or self.timeout)
        wait.until(EC.presence_of_all_elements_located(locator))
        return self.driver.find_elements(*locator)

    def is_visible(self, locator: Locator, timeout: int = 3) -> bool:
        """Return True if element is visible, False otherwise."""
        try:
            WebDriverWait(self.driver, timeout).until(
                EC.visibility_of_element_located(locator)
            )
            return True
        except (TimeoutException, NoSuchElementException):
            return False

    def is_present(self, locator: Locator, timeout: int = 3) -> bool:
        """Return True if element is present in DOM (may not be visible)."""
        try:
            WebDriverWait(self.driver, timeout).until(
                EC.presence_of_element_located(locator)
            )
            return True
        except (TimeoutException, NoSuchElementException):
            return False

    # ──────────────────────────────────────────────
    # Interactions
    # ──────────────────────────────────────────────

    def click(self, locator: Locator, timeout: int = None) -> "BasePage":
        """
        Click an element. Falls back to JS click if intercepted.

        Handles ElementClickInterceptedException automatically.
        """
        element = self.find_clickable(locator, timeout)
        try:
            element.click()
        except ElementClickInterceptedException:
            # Fallback: JS click (handles overlays/popups)
            self.driver.execute_script("arguments[0].click();", element)
        return self

    def type(self, locator: Locator, text: str, clear_first: bool = True) -> "BasePage":
        """
        Type text into an input field.

        Args:
            locator: Element locator
            text: Text to type
            clear_first: Clear existing text before typing (default: True)
        """
        element = self.find(locator)
        if clear_first:
            element.clear()
        element.send_keys(text)
        return self

    def clear(self, locator: Locator) -> "BasePage":
        """Clear an input field using Ctrl+A + Delete (more reliable than .clear())."""
        element = self.find(locator)
        element.send_keys(Keys.CONTROL + "a")
        element.send_keys(Keys.DELETE)
        return self

    def submit(self, locator: Locator) -> "BasePage":
        """Submit a form by pressing Enter on an element."""
        self.find(locator).send_keys(Keys.RETURN)
        return self

    def select_by_text(self, locator: Locator, text: str) -> "BasePage":
        """Select dropdown option by visible text."""
        Select(self.find(locator)).select_by_visible_text(text)
        return self

    def select_by_value(self, locator: Locator, value: str) -> "BasePage":
        """Select dropdown option by value attribute."""
        Select(self.find(locator)).select_by_value(value)
        return self

    def select_by_index(self, locator: Locator, index: int) -> "BasePage":
        """Select dropdown option by index."""
        Select(self.find(locator)).select_by_index(index)
        return self

    # ──────────────────────────────────────────────
    # Getting Values
    # ──────────────────────────────────────────────

    def get_text(self, locator: Locator) -> str:
        """Get visible text of an element."""
        return self.find(locator).text

    def get_value(self, locator: Locator) -> str:
        """Get value attribute of an input field."""
        return self.find(locator).get_attribute("value") or ""

    def get_attribute(self, locator: Locator, attribute: str) -> str:
        """Get any attribute value of an element."""
        return self.find(locator).get_attribute(attribute) or ""

    def is_checked(self, locator: Locator) -> bool:
        """Return True if checkbox/radio is checked."""
        return self.find(locator).is_selected()

    def is_enabled(self, locator: Locator) -> bool:
        """Return True if element is enabled."""
        return self.find(locator).is_enabled()

    # ──────────────────────────────────────────────
    # Waiting
    # ──────────────────────────────────────────────

    def wait_for_url(self, url_contains: str, timeout: int = None) -> "BasePage":
        """Wait until URL contains the given string."""
        WebDriverWait(self.driver, timeout or self.timeout).until(
            EC.url_contains(url_contains)
        )
        return self

    def wait_for_title(self, title_contains: str, timeout: int = None) -> "BasePage":
        """Wait until page title contains the given string."""
        WebDriverWait(self.driver, timeout or self.timeout).until(
            EC.title_contains(title_contains)
        )
        return self

    def wait_for_invisible(self, locator: Locator, timeout: int = None) -> "BasePage":
        """Wait until element disappears (e.g. loading spinner)."""
        WebDriverWait(self.driver, timeout or self.timeout).until(
            EC.invisibility_of_element_located(locator)
        )
        return self

    def wait_for_text(self, locator: Locator, text: str, timeout: int = None) -> "BasePage":
        """Wait until element contains specific text."""
        WebDriverWait(self.driver, timeout or self.timeout).until(
            EC.text_to_be_present_in_element(locator, text)
        )
        return self

    # ──────────────────────────────────────────────
    # Scrolling & Hover
    # ──────────────────────────────────────────────

    def scroll_to(self, locator: Locator) -> "BasePage":
        """Scroll element into view."""
        element = self.find(locator)
        self.driver.execute_script("arguments[0].scrollIntoView({block: 'center'});", element)
        return self

    def scroll_to_top(self) -> "BasePage":
        """Scroll to top of page."""
        self.driver.execute_script("window.scrollTo(0, 0);")
        return self

    def scroll_to_bottom(self) -> "BasePage":
        """Scroll to bottom of page."""
        self.driver.execute_script("window.scrollTo(0, document.body.scrollHeight);")
        return self

    def hover(self, locator: Locator) -> "BasePage":
        """Hover over an element."""
        element = self.find(locator)
        ActionChains(self.driver).move_to_element(element).perform()
        return self

    def drag_and_drop(self, source: Locator, target: Locator) -> "BasePage":
        """Drag element from source to target."""
        src = self.find(source)
        tgt = self.find(target)
        ActionChains(self.driver).drag_and_drop(src, tgt).perform()
        return self

    # ──────────────────────────────────────────────
    # Alerts & Frames
    # ──────────────────────────────────────────────

    def accept_alert(self, timeout: int = 5) -> str:
        """Accept JS alert and return its text."""
        WebDriverWait(self.driver, timeout).until(EC.alert_is_present())
        alert = self.driver.switch_to.alert
        text = alert.text
        alert.accept()
        return text

    def dismiss_alert(self, timeout: int = 5) -> str:
        """Dismiss JS alert/confirm and return its text."""
        WebDriverWait(self.driver, timeout).until(EC.alert_is_present())
        alert = self.driver.switch_to.alert
        text = alert.text
        alert.dismiss()
        return text

    def switch_to_frame(self, locator: Locator) -> "BasePage":
        """Switch WebDriver context to an iframe."""
        frame = self.find(locator)
        self.driver.switch_to.frame(frame)
        return self

    def switch_to_default(self) -> "BasePage":
        """Switch back to main document from iframe."""
        self.driver.switch_to.default_content()
        return self

    # ──────────────────────────────────────────────
    # Screenshots & Debugging
    # ──────────────────────────────────────────────

    def screenshot(self, filename: str = None) -> str:
        """
        Take a screenshot and save it.

        Args:
            filename: Custom filename (auto-generated if not provided)

        Returns:
            str: Path to saved screenshot
        """
        os.makedirs("screenshots", exist_ok=True)
        if not filename:
            timestamp = datetime.now().strftime("%Y%m%d_%H%M%S")
            filename = f"screenshots/screenshot_{timestamp}.png"
        self.driver.save_screenshot(filename)
        return filename

    def screenshot_on_failure(self, test_name: str) -> str:
        """Take screenshot named after the failing test."""
        return self.screenshot(f"screenshots/FAILED_{test_name}.png")

    def get_page_source(self) -> str:
        """Return full HTML source of the page."""
        return self.driver.page_source

    def execute_js(self, script: str, *args) -> object:
        """Execute JavaScript on the page."""
        return self.driver.execute_script(script, *args)

    # ──────────────────────────────────────────────
    # Window & Tab Management
    # ──────────────────────────────────────────────

    def switch_to_new_window(self) -> "BasePage":
        """Switch to newly opened window/tab."""
        WebDriverWait(self.driver, self.timeout).until(
            EC.number_of_windows_to_be(2)
        )
        self.driver.switch_to.window(self.driver.window_handles[-1])
        return self

    def close_current_window(self) -> "BasePage":
        """Close current window and switch back to first."""
        self.driver.close()
        self.driver.switch_to.window(self.driver.window_handles[0])
        return self
